#!/bin/bash
# Transformer 项目快速启动脚本

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║           🚀 Transformer 架构从零实现 - 项目启动 🚀                    ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "项目已准备就绪！"
echo ""
echo "📍 项目位置：$(pwd)"
echo ""
echo "🔧 推荐的启动方式："
echo ""
echo "  1️⃣  交互式学习（最推荐）⭐"
echo "     $ python demo.py"
echo ""
echo "  2️⃣  查看项目说明"
echo "     $ python setup.py"
echo ""
echo "  3️⃣  查看完成总结"
echo "     $ python FINAL_SUMMARY.py"
echo ""
echo "  4️⃣  逐个学习模块"
echo "     $ python src/01_positional_encoding.py"
echo "     $ python src/02_attention.py"
echo "     $ python src/04_feed_forward.py"
echo "     $ python src/05_encoder_layer.py"
echo "     $ python src/06_decoder_layer.py"
echo "     $ python src/07_transformer.py"
echo ""
echo "  5️⃣  运行训练示例"
echo "     $ python examples/train_example.py"
echo ""
echo "  6️⃣  查看详细指南"
echo "     $ cat README_START.md"
echo "     $ cat QUICKSTART.md"
echo ""
echo "💡 首次运行？"
echo "   建议先运行：python demo.py"
echo ""
echo "📦 需要安装依赖？"
echo "   运行：pip install -r requirements.txt"
echo ""
echo "❓ 遇到问题？"
echo "   查看：README_START.md 或 QUICKSTART.md"
echo ""
echo "┌────────────────────────────────────────────────────────────────────────┐"
echo "│                    选择一个命令开始学习吧！                            │"
echo "└────────────────────────────────────────────────────────────────────────┘"
echo ""
